# .github/workflows/ci.yml
name: CI Pipeline

on:
  push:
    branches: [main, develop] 
  pull_request:
    branches: [main] 

jobs:
  build:
    runs-on: ubuntu-latest 
    
    steps:
      - name: 1. Checkout del código
        uses: actions/checkout@v4

      - name: 2. Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 3. Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest pytest-cov bandit 

      - name: 4. Ejecutar linter (Estilo de código)
        run: flake8 . [cite_start]--count --select=E9,F63,F7,F82 --show-source --statistics

      - name: 5. Análisis de seguridad
        run: bandit -r . [cite_start]-x ./tests

      - name: 6. Tests unitarios y Cobertura
        run: pytest --cov=calculadora